// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGBnVOV5JiYkqcX2TMbpurIz8hIxFFlHM',
    appId: '1:184201308015:web:243114a412966789592a9a',
    messagingSenderId: '184201308015',
    projectId: 'mizan-97a67',
    authDomain: 'mizan-97a67.firebaseapp.com',
    storageBucket: 'mizan-97a67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGCPUfOkEaEcSknzwH9_Z6KMnM5An_80',
    appId: '1:184201308015:android:b187b8d637ec46a2592a9a',
    messagingSenderId: '184201308015',
    projectId: 'mizan-97a67',
    storageBucket: 'mizan-97a67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5QtscJuWp6d1IJpSQ5ucjhJxonUovt1I',
    appId: '1:184201308015:ios:f059ef30e16978c7592a9a',
    messagingSenderId: '184201308015',
    projectId: 'mizan-97a67',
    storageBucket: 'mizan-97a67.firebasestorage.app',
    iosBundleId: 'com.example.sadaqahJar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5QtscJuWp6d1IJpSQ5ucjhJxonUovt1I',
    appId: '1:184201308015:ios:f059ef30e16978c7592a9a',
    messagingSenderId: '184201308015',
    projectId: 'mizan-97a67',
    storageBucket: 'mizan-97a67.firebasestorage.app',
    iosBundleId: 'com.example.sadaqahJar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGBnVOV5JiYkqcX2TMbpurIz8hIxFFlHM',
    appId: '1:184201308015:web:09b98cbda61cdc38592a9a',
    messagingSenderId: '184201308015',
    projectId: 'mizan-97a67',
    authDomain: 'mizan-97a67.firebaseapp.com',
    storageBucket: 'mizan-97a67.firebasestorage.app',
  );
}
